server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # module workers (MapLibre) must be served with a JavaScript MIME type
  types {
    application/javascript mjs;
  }

  location / {
    try_files $uri /index.html;
  }
}
