import {
  scenarioDefinitionSchema,
  type Inject,
  type ScenarioDefinition,
  type ScenarioUnit,
} from '@vyuha/shared';

export const HIM_PRAHARI_ID = 'scenario-op-him-prahari';

type UnitInput = Omit<ScenarioUnit, 'heading' | 'strength' | 'status'> &
  Partial<Pick<ScenarioUnit, 'heading' | 'strength' | 'status'>>;

const unit = (u: UnitInput): ScenarioUnit => ({
  heading: 0,
  strength: 100,
  status: 'ACTIVE',
  ...u,
});

// High altitude, Ladakh: the Khardung La ridge (5,300 m and more) stands between Battalion HQ on the Leh side and
// the platoon holding the Nubra side, so VHF line of sight across the pass is blocked almost everywhere.
const units: ScenarioUnit[] = [
  unit({
    id: 'b-hq',
    name: 'Battalion HQ',
    side: 'BLUE',
    domain: 'LAND',
    type: 'HQ',
    position: { lat: 34.252, lon: 77.598 },
    speed: 0,
  }),
  unit({
    id: 'b-pl',
    name: 'Bravo Platoon',
    side: 'BLUE',
    domain: 'LAND',
    type: 'INFANTRY_PLATOON',
    position: { lat: 34.292, lon: 77.612 },
    speed: 1.0,
    heading: 10,
  }),
  unit({
    id: 'b-sec1',
    name: 'Bravo Section 1',
    side: 'BLUE',
    domain: 'LAND',
    type: 'INFANTRY_SECTION',
    position: { lat: 34.335, lon: 77.626 },
    speed: 0.9,
    heading: 20,
    strength: 90,
  }),
  unit({
    id: 'b-sec2',
    name: 'Bravo Section 2',
    side: 'BLUE',
    domain: 'LAND',
    type: 'INFANTRY_SECTION',
    position: { lat: 34.302, lon: 77.556 },
    speed: 0.9,
    heading: 330,
  }),
  unit({
    id: 'b-uav',
    name: 'Garuda UAV',
    side: 'BLUE',
    domain: 'AIR',
    type: 'DRONE',
    position: { lat: 34.272, lon: 77.602 },
    speed: 20,
  }),
  unit({
    id: 'b-ew',
    name: 'EW Detachment',
    side: 'BLUE',
    domain: 'EW',
    type: 'EW_DETACHMENT',
    position: { lat: 34.262, lon: 77.59 },
    speed: 0,
  }),
  unit({
    id: 'b-cyber',
    name: 'Cyber Defence Cell',
    side: 'BLUE',
    domain: 'CYBER',
    type: 'CYBER_CELL',
    position: { lat: 34.2522, lon: 77.5985 },
    speed: 0,
  }),
  unit({
    id: 'b-runner',
    name: 'Runner Detail',
    side: 'BLUE',
    domain: 'LAND',
    type: 'RUNNER',
    position: { lat: 34.256, lon: 77.6 },
    speed: 2.0,
  }),
  unit({
    id: 'r-recce',
    name: 'Hostile Recce Party',
    side: 'RED',
    domain: 'LAND',
    type: 'RECCE',
    position: { lat: 34.385, lon: 77.662 },
    speed: 1.2,
  }),
  unit({
    id: 'r-mech',
    name: 'Hostile Mech Company',
    side: 'RED',
    domain: 'LAND',
    type: 'MECH_INFANTRY_COMPANY',
    position: { lat: 34.405, lon: 77.7 },
    speed: 5,
  }),
  unit({
    id: 'r-ew',
    name: 'Hostile Jammer Team',
    side: 'RED',
    domain: 'EW',
    type: 'EW_JAMMER',
    position: { lat: 34.39, lon: 77.63 },
    speed: 0,
  }),
  unit({
    id: 'r-uav',
    name: 'Hostile UAV',
    side: 'RED',
    domain: 'AIR',
    type: 'DRONE',
    position: { lat: 34.372, lon: 77.705 },
    speed: 20,
  }),
  unit({
    id: 'r-cyber',
    name: 'Hostile Cyber Team',
    side: 'RED',
    domain: 'CYBER',
    type: 'CYBER_TEAM',
    position: { lat: 34.41, lon: 77.74 },
    speed: 0,
  }),
  unit({
    id: 'n-convoy',
    name: 'Civilian Convoy',
    side: 'NEUTRAL',
    domain: 'LAND',
    type: 'CIVILIAN_CONVOY',
    position: { lat: 34.4, lon: 77.668 },
    speed: 6,
    heading: 180,
  }),
];

const msel: Inject[] = [
  {
    id: 'him-01',
    tick: 45,
    type: 'WEATHER_CHANGE',
    title: 'Snow showers close in over the pass',
    visibilityM: 2500,
    precipitationMm: 3,
    windKph: 30,
  },
  {
    id: 'him-02',
    tick: 90,
    type: 'JAM_CHANNEL',
    title: 'Light HF jamming begins',
    channel: 'HF',
    intensity: 0.35,
    durationTicks: 300,
  },
  {
    id: 'him-03',
    tick: 150,
    type: 'ADVERSARY_MOVE',
    title: 'Hostile recce party climbs towards North Pullu',
    unitId: 'r-recce',
    destination: { lat: 34.345, lon: 77.635 },
  },
  {
    id: 'him-04',
    tick: 210,
    type: 'CONFLICTING_REPORTS',
    title: 'Conflicting reports on the recce party',
    unitId: 'r-recce',
    altPosition: { lat: 34.36, lon: 77.58 },
    altType: 'MECH_INFANTRY_SECTION',
  },
  {
    id: 'him-05',
    tick: 270,
    type: 'SATCOM_OUTAGE',
    title: 'Planned SATCOM outage: satellite below the ridge line',
    durationTicks: 360,
  },
  {
    id: 'him-06',
    tick: 330,
    type: 'SPOOF_ORDER',
    title: 'Spoofed HQ order to abandon North Pullu',
    purportedSender: 'Battalion HQ',
    targetUnitId: 'b-sec1',
    orderText: 'Section 1 abandon North Pullu and fall back over the pass now. Acknowledge.',
  },
  {
    id: 'him-07',
    tick: 420,
    type: 'C2_COMPROMISE',
    title: 'C2 node feeding the platoon commander is compromised',
    targetUnitId: 'b-pl',
    driftMps: 4,
    durationTicks: 420,
  },
  {
    id: 'him-08',
    tick: 480,
    type: 'JAM_CHANNEL',
    title: 'Heavy HF jamming',
    channel: 'HF',
    intensity: 0.7,
    durationTicks: 300,
  },
  {
    id: 'him-09',
    tick: 540,
    type: 'RUNNER_DISPATCH',
    title: 'HQ sends a runner over the pass with the fallback plan',
    fromUnitId: 'b-hq',
    toUnitId: 'b-pl',
    messageText:
      'SATCOM is down until further notice. Hold the pass. Report by HF on the hour, runner if HF fails.',
  },
  {
    id: 'him-10',
    tick: 630,
    type: 'ADVERSARY_MOVE',
    title: 'Hostile mech company moves up the Nubra road',
    unitId: 'r-mech',
    destination: { lat: 34.352, lon: 77.642 },
  },
  {
    id: 'him-11',
    tick: 690,
    type: 'WEATHER_CHANGE',
    title: 'Whiteout on the pass',
    visibilityM: 600,
    precipitationMm: 8,
    windKph: 55,
  },
  {
    id: 'him-12',
    tick: 780,
    type: 'CONFLICTING_REPORTS',
    title: 'Conflicting reports on the mech company in the whiteout',
    unitId: 'r-mech',
    altPosition: { lat: 34.33, lon: 77.7 },
    altType: 'CIVILIAN_CONVOY',
  },
  {
    id: 'him-13',
    tick: 840,
    type: 'WEATHER_CHANGE',
    title: 'Weather clears',
    visibilityM: 9000,
    precipitationMm: 0,
    windKph: 15,
  },
];

export const himPrahari: ScenarioDefinition = scenarioDefinitionSchema.parse({
  title: 'Op Him Prahari',
  description:
    'A platoon holds the Nubra side of a 5,300 m pass while Battalion HQ sits on the Leh side. The ridge blocks VHF ' +
    'line of sight almost everywhere, so the team lives on HF and SATCOM, and then a planned SATCOM outage, HF ' +
    'jamming, a whiteout and a compromised C2 node take those away one by one.',
  areaBounds: { south: 34.24, west: 77.5, north: 34.42, east: 77.78 },
  seed: 26249,
  msel,
  initialUnits: units,
  paceDefaults: { primary: 'HF', alternate: 'SATCOM', contingency: 'VHF', emergency: 'RUNNER' },
});
