import {
  scenarioDefinitionSchema,
  type Inject,
  type ScenarioDefinition,
  type ScenarioUnit,
} from '@vyuha/shared';

export const SILENT_RIDGE_ID = 'scenario-op-silent-ridge';

type UnitInput = Omit<ScenarioUnit, 'heading' | 'strength' | 'status'> &
  Partial<Pick<ScenarioUnit, 'heading' | 'strength' | 'status'>>;

const unit = (u: UnitInput): ScenarioUnit => ({
  heading: 0,
  strength: 100,
  status: 'ACTIVE',
  ...u,
});

// Positions sit inside the Leh-Ladakh bounding box below (Indus valley floor around Leh, ridgelines to the north).
const units: ScenarioUnit[] = [
  unit({
    id: 'b-hq',
    name: 'Battalion HQ',
    side: 'BLUE',
    domain: 'LAND',
    type: 'HQ',
    position: { lat: 34.153, lon: 77.577 },
    speed: 0,
  }),
  unit({
    id: 'b-pl',
    name: 'Alpha Platoon',
    side: 'BLUE',
    domain: 'LAND',
    type: 'INFANTRY_PLATOON',
    position: { lat: 34.175, lon: 77.59 },
    heading: 20,
    speed: 1.2,
  }),
  unit({
    id: 'b-sec1',
    name: 'Alpha Section 1',
    side: 'BLUE',
    domain: 'LAND',
    type: 'INFANTRY_SECTION',
    position: { lat: 34.195, lon: 77.615 },
    heading: 35,
    speed: 1.1,
    strength: 90,
  }),
  unit({
    id: 'b-sec2',
    name: 'Alpha Section 2',
    side: 'BLUE',
    domain: 'LAND',
    type: 'INFANTRY_SECTION',
    position: { lat: 34.185, lon: 77.54 },
    heading: 340,
    speed: 1.1,
    strength: 95,
  }),
  unit({
    id: 'b-uav',
    name: 'Falcon UAV',
    side: 'BLUE',
    domain: 'AIR',
    type: 'DRONE',
    position: { lat: 34.19, lon: 77.58 },
    heading: 45,
    speed: 22,
  }),
  unit({
    id: 'b-ew',
    name: 'EW Detachment',
    side: 'BLUE',
    domain: 'EW',
    type: 'EW_DETACHMENT',
    position: { lat: 34.165, lon: 77.56 },
    speed: 0,
  }),
  unit({
    id: 'b-cyber',
    name: 'Cyber Defence Cell',
    side: 'BLUE',
    domain: 'CYBER',
    type: 'CYBER_CELL',
    position: { lat: 34.1532, lon: 77.578 },
    speed: 0,
  }),
  unit({
    id: 'b-runner',
    name: 'Runner Detail',
    side: 'BLUE',
    domain: 'LAND',
    type: 'RUNNER',
    position: { lat: 34.16, lon: 77.575 },
    speed: 2.5,
  }),
  unit({
    id: 'r-recce',
    name: 'Hostile Recce Party',
    side: 'RED',
    domain: 'LAND',
    type: 'RECCE',
    position: { lat: 34.23, lon: 77.63 },
    heading: 200,
    speed: 1.4,
    strength: 60,
  }),
  unit({
    id: 'r-mech',
    name: 'Hostile Mech Company',
    side: 'RED',
    domain: 'LAND',
    type: 'MECH_INFANTRY_COMPANY',
    position: { lat: 34.24, lon: 77.5 },
    heading: 160,
    speed: 6,
  }),
  unit({
    id: 'r-ew',
    name: 'Hostile Jammer Team',
    side: 'RED',
    domain: 'EW',
    type: 'EW_JAMMER',
    position: { lat: 34.22, lon: 77.56 },
    speed: 0,
  }),
  unit({
    id: 'r-uav',
    name: 'Hostile UAV',
    side: 'RED',
    domain: 'AIR',
    type: 'DRONE',
    position: { lat: 34.245, lon: 77.6 },
    heading: 190,
    speed: 20,
  }),
  unit({
    id: 'r-cyber',
    name: 'Hostile Cyber Team',
    side: 'RED',
    domain: 'CYBER',
    type: 'CYBER_TEAM',
    position: { lat: 34.25, lon: 77.65 },
    speed: 0,
  }),
  unit({
    id: 'n-convoy',
    name: 'Civilian Convoy',
    side: 'NEUTRAL',
    domain: 'LAND',
    type: 'CIVILIAN_CONVOY',
    position: { lat: 34.14, lon: 77.59 },
    heading: 90,
    speed: 8,
  }),
];

const msel: Inject[] = [
  {
    id: 'inj-01',
    tick: 60,
    type: 'JAM_CHANNEL',
    title: 'Light VHF jamming begins',
    channel: 'VHF',
    intensity: 0.3,
    durationTicks: 300,
  },
  {
    id: 'inj-02',
    tick: 120,
    type: 'CONFLICTING_REPORTS',
    title: 'Conflicting reports on hostile recce party',
    unitId: 'r-recce',
    altPosition: { lat: 34.205, lon: 77.66 },
    altType: 'MECH_INFANTRY_SECTION',
  },
  {
    id: 'inj-03',
    tick: 180,
    type: 'ADVERSARY_MOVE',
    title: 'Hostile mech company advances east',
    unitId: 'r-mech',
    destination: { lat: 34.2, lon: 77.54 },
  },
  {
    id: 'inj-04',
    tick: 240,
    type: 'SPOOF_ORDER',
    title: 'Spoofed HQ order to withdraw Section 1',
    purportedSender: 'Battalion HQ',
    targetUnitId: 'b-sec1',
    orderText: 'Section 1 withdraw immediately to grid 34.15N 77.55E. Acknowledge.',
  },
  {
    id: 'inj-05',
    tick: 300,
    type: 'WEATHER_CHANGE',
    title: 'Low cloud and snow showers reduce visibility',
    visibilityM: 1500,
    precipitationMm: 4,
    windKph: 28,
  },
  {
    id: 'inj-06',
    tick: 360,
    type: 'JAM_CHANNEL',
    title: 'Heavy VHF jamming from ridge-line jammer',
    channel: 'VHF',
    intensity: 0.75,
    durationTicks: 420,
  },
  {
    id: 'inj-07',
    tick: 420,
    type: 'RUNNER_DISPATCH',
    title: 'HQ dispatches runner with revised phase line',
    fromUnitId: 'b-hq',
    toUnitId: 'b-pl',
    messageText: 'Hold phase line GOLD until further orders. Confirm by runner only.',
  },
  {
    id: 'inj-08',
    tick: 480,
    type: 'SATCOM_OUTAGE',
    title: 'Cyber attack takes SATCOM down',
    durationTicks: 300,
  },
  {
    id: 'inj-09',
    tick: 540,
    type: 'CONFLICTING_REPORTS',
    title: 'Conflicting reports on UAV contact near Section 2',
    unitId: 'r-uav',
    altPosition: { lat: 34.21, lon: 77.52 },
    altType: 'CIVILIAN_AIRCRAFT',
  },
  {
    id: 'inj-10',
    tick: 600,
    type: 'JAM_CHANNEL',
    title: 'Datalink jamming',
    channel: 'DATALINK',
    intensity: 0.6,
    durationTicks: 300,
  },
  {
    id: 'inj-11',
    tick: 660,
    type: 'SPOOF_ORDER',
    title: 'Spoofed order directing UAV to land',
    purportedSender: 'Battalion HQ',
    targetUnitId: 'b-uav',
    orderText: 'Falcon UAV return to base and land now. Radio silence on VHF.',
  },
  {
    id: 'inj-12',
    tick: 720,
    type: 'ADVERSARY_MOVE',
    title: 'Hostile recce party moves to the ridge',
    unitId: 'r-recce',
    destination: { lat: 34.2, lon: 77.62 },
  },
  {
    id: 'inj-13',
    tick: 780,
    type: 'WEATHER_CHANGE',
    title: 'Weather clears',
    visibilityM: 8000,
    precipitationMm: 0,
    windKph: 12,
  },
  {
    id: 'inj-14',
    tick: 840,
    type: 'RUNNER_DISPATCH',
    title: 'Section 2 sends runner to HQ with contact report',
    fromUnitId: 'b-sec2',
    toUnitId: 'b-hq',
    messageText: 'Hostile vehicles observed on road north of Section 2. Strength approx 6.',
  },
];

export const silentRidge: ScenarioDefinition = scenarioDefinitionSchema.parse({
  title: 'Op Silent Ridge',
  description:
    'A blue platoon holds the Indus valley approaches to Leh while a hostile force probes from the northern ridgelines. ' +
    'Ridge-masked VHF, reliance-adaptive jamming, a SATCOM cyber outage and spoofed HQ orders force the team to ' +
    'reconcile conflicting pictures and fall back on PACE alternatives.',
  areaBounds: { south: 34.08, west: 77.45, north: 34.26, east: 77.7 },
  seed: 26248,
  msel,
  initialUnits: units,
  paceDefaults: { primary: 'VHF', alternate: 'HF', contingency: 'SATCOM', emergency: 'RUNNER' },
});
