import {
  scenarioDefinitionSchema,
  type Inject,
  type ScenarioDefinition,
  type ScenarioUnit,
} from '@vyuha/shared';

export const THAR_KAVACH_ID = 'scenario-op-thar-kavach';

type UnitInput = Omit<ScenarioUnit, 'heading' | 'strength' | 'status'> &
  Partial<Pick<ScenarioUnit, 'heading' | 'strength' | 'status'>>;

const unit = (u: UnitInput): ScenarioUnit => ({
  heading: 0,
  strength: 100,
  status: 'ACTIVE',
  ...u,
});

// Desert, western Rajasthan (the flats around Ramgarh, north-west of Jaisalmer): almost no relief, so VHF reaches
// across the whole area, which is exactly why the adversary jams it hard. HQ, the platoon and the sections sit
// on dune crests picked from the real elevation grid, so they have line of sight to each other.
const units: ScenarioUnit[] = [
  unit({
    id: 'b-hq',
    name: 'Battalion HQ',
    side: 'BLUE',
    domain: 'LAND',
    type: 'HQ',
    position: { lat: 27.307, lon: 70.515 },
    speed: 0,
  }),
  unit({
    id: 'b-pl',
    name: 'Charlie Platoon',
    side: 'BLUE',
    domain: 'LAND',
    type: 'INFANTRY_PLATOON',
    position: { lat: 27.3745, lon: 70.4745 },
    speed: 1.6,
    heading: 0,
  }),
  unit({
    id: 'b-sec1',
    name: 'Charlie Section 1',
    side: 'BLUE',
    domain: 'LAND',
    type: 'INFANTRY_SECTION',
    position: { lat: 27.387, lon: 70.5395 },
    speed: 1.5,
    heading: 30,
    strength: 90,
  }),
  unit({
    id: 'b-sec2',
    name: 'Charlie Section 2',
    side: 'BLUE',
    domain: 'LAND',
    type: 'INFANTRY_SECTION',
    position: { lat: 27.3785, lon: 70.437 },
    speed: 1.5,
    heading: 340,
  }),
  unit({
    id: 'b-uav',
    name: 'Baaz UAV',
    side: 'BLUE',
    domain: 'AIR',
    type: 'DRONE',
    position: { lat: 27.352, lon: 70.5 },
    speed: 24,
  }),
  unit({
    id: 'b-ew',
    name: 'EW Detachment',
    side: 'BLUE',
    domain: 'EW',
    type: 'EW_DETACHMENT',
    position: { lat: 27.325, lon: 70.495 },
    speed: 0,
  }),
  unit({
    id: 'b-cyber',
    name: 'Cyber Defence Cell',
    side: 'BLUE',
    domain: 'CYBER',
    type: 'CYBER_CELL',
    position: { lat: 27.3072, lon: 70.516 },
    speed: 0,
  }),
  unit({
    id: 'b-runner',
    name: 'Runner Detail',
    side: 'BLUE',
    domain: 'LAND',
    type: 'RUNNER',
    position: { lat: 27.311, lon: 70.513 },
    speed: 3.0,
  }),
  unit({
    id: 'r-recce',
    name: 'Hostile Recce Party',
    side: 'RED',
    domain: 'LAND',
    type: 'RECCE',
    position: { lat: 27.45, lon: 70.58 },
    speed: 2.0,
  }),
  unit({
    id: 'r-mech',
    name: 'Hostile Mech Company',
    side: 'RED',
    domain: 'LAND',
    type: 'MECH_INFANTRY_COMPANY',
    position: { lat: 27.465, lon: 70.5 },
    speed: 9,
  }),
  unit({
    id: 'r-ew',
    name: 'Hostile Jammer Team',
    side: 'RED',
    domain: 'EW',
    type: 'EW_JAMMER',
    position: { lat: 27.46, lon: 70.55 },
    speed: 0,
  }),
  unit({
    id: 'r-uav',
    name: 'Hostile UAV',
    side: 'RED',
    domain: 'AIR',
    type: 'DRONE',
    position: { lat: 27.442, lon: 70.602 },
    speed: 22,
  }),
  unit({
    id: 'r-cyber',
    name: 'Hostile Cyber Team',
    side: 'RED',
    domain: 'CYBER',
    type: 'CYBER_TEAM',
    position: { lat: 27.47, lon: 70.62 },
    speed: 0,
  }),
  unit({
    id: 'n-convoy',
    name: 'Civilian Convoy',
    side: 'NEUTRAL',
    domain: 'LAND',
    type: 'CIVILIAN_CONVOY',
    position: { lat: 27.42, lon: 70.46 },
    speed: 10,
    heading: 90,
  }),
];

const msel: Inject[] = [
  {
    id: 'thar-01',
    tick: 60,
    type: 'JAM_CHANNEL',
    title: 'VHF jamming begins from the dune line',
    channel: 'VHF',
    intensity: 0.5,
    durationTicks: 240,
  },
  {
    id: 'thar-02',
    tick: 120,
    type: 'ADVERSARY_MOVE',
    title: 'Hostile mech company advances south across the flats',
    unitId: 'r-mech',
    destination: { lat: 27.41, lon: 70.49 },
  },
  {
    id: 'thar-03',
    tick: 180,
    type: 'GPS_SPOOF',
    title: 'UAV navigation spoofed: Baaz reports everything 2.5 km off',
    unitId: 'b-uav',
    offsetM: 2500,
    bearingDeg: 135,
    durationTicks: 420,
  },
  {
    id: 'thar-04',
    tick: 240,
    type: 'CONFLICTING_REPORTS',
    title: 'Conflicting reports on the mech company',
    unitId: 'r-mech',
    altPosition: { lat: 27.44, lon: 70.44 },
    altType: 'MECH_INFANTRY_SECTION',
  },
  {
    id: 'thar-05',
    tick: 300,
    type: 'JAM_CHANNEL',
    title: 'Heavy VHF jamming',
    channel: 'VHF',
    intensity: 0.85,
    durationTicks: 360,
  },
  {
    id: 'thar-06',
    tick: 360,
    type: 'SPOOF_ORDER',
    title: 'Spoofed HQ order to pull Section 2 off the flank',
    purportedSender: 'Battalion HQ',
    targetUnitId: 'b-sec2',
    orderText:
      'Section 2 leave the western flank and rejoin HQ at once. Do not acknowledge on VHF.',
  },
  {
    id: 'thar-07',
    tick: 420,
    type: 'WEATHER_CHANGE',
    title: 'Dust storm cuts visibility',
    visibilityM: 900,
    precipitationMm: 0,
    windKph: 55,
  },
  {
    id: 'thar-08',
    tick: 480,
    type: 'JAM_CHANNEL',
    title: 'Data-link jamming',
    channel: 'DATALINK',
    intensity: 0.7,
    durationTicks: 300,
  },
  {
    id: 'thar-09',
    tick: 540,
    type: 'RUNNER_DISPATCH',
    title: 'HQ sends a vehicle-borne runner with new report lines',
    fromUnitId: 'b-hq',
    toUnitId: 'b-pl',
    messageText:
      'VHF is being jammed. Use HF for reports and confirm every UAV contact with a second source.',
  },
  {
    id: 'thar-10',
    tick: 600,
    type: 'SATCOM_OUTAGE',
    title: 'SATCOM terminal attacked',
    durationTicks: 180,
  },
  {
    id: 'thar-11',
    tick: 660,
    type: 'ADVERSARY_MOVE',
    title: 'Hostile recce party probes the eastern flank',
    unitId: 'r-recce',
    destination: { lat: 27.405, lon: 70.565 },
  },
  {
    id: 'thar-12',
    tick: 720,
    type: 'JAM_CHANNEL',
    title: 'HF jamming joins in',
    channel: 'HF',
    intensity: 0.5,
    durationTicks: 240,
  },
  {
    id: 'thar-13',
    tick: 780,
    type: 'WEATHER_CHANGE',
    title: 'Dust settles',
    visibilityM: 12000,
    precipitationMm: 0,
    windKph: 14,
  },
];

export const tharKavach: ScenarioDefinition = scenarioDefinitionSchema.parse({
  title: 'Op Thar Kavach',
  description:
    'A platoon screens open desert where line of sight runs for kilometres and VHF reaches everyone, until the ' +
    'adversary jams it hard. The team must move down its PACE plan while its own UAV, its best eyes on the flats, ' +
    'has its navigation spoofed and quietly reports every contact 2.5 km from where it really is.',
  areaBounds: { south: 27.3, west: 70.36, north: 27.48, east: 70.64 },
  seed: 26250,
  msel,
  initialUnits: units,
  paceDefaults: { primary: 'VHF', alternate: 'DATALINK', contingency: 'HF', emergency: 'RUNNER' },
});
